// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const left: string;
export const right: string;
export const headline: string;
export const title: string;
export const bookmarkButton: string;
