export const data = [
    {
        id: 73878,
        name: 'Motel 6 San Francisco',
        type: 'Motel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/73/87/73878_v4.jpeg',
        rating: 1,
        reviewCount: 141,
        category: 2,
        price: 116,
    },
    {
        id: 56238,
        name: 'Holiday Inn Express & Suites San Francisco Fishermans Wharf',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/56/23/56238_v4.jpeg',
        rating: 4,
        reviewCount: 4734,
        category: 3,
        price: 176,
    },
    {
        id: 66840,
        name: 'Parc 55 San Francisco a Hilton Hotel',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/66/84/66840_v12.jpeg',
        rating: 4,
        reviewCount: 16917,
        category: 4,
        price: 327,
    },
    {
        id: 1211622,
        name: 'Motel Capri',
        type: 'Motel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/12/11/1211622_v5.jpeg',
        rating: 2,
        reviewCount: 3070,
        category: 5,
        price: 96,
    },
    {
        id: 357256,
        name: 'InterContinental San Francisco',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/35/72/357256_v7.jpeg',
        rating: 5,
        reviewCount: 4446,
        category: 4,
        price: 367,
    },
    {
        id: 8019,
        name: 'Argonaut Hotel',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/80/19/8019_v10.jpeg',
        rating: 5,
        reviewCount: 17610,
        category: 4,
        price: 339,
    },
    {
        id: 7990,
        name: 'Fairmont San Francisco',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/79/90/7990_v14.jpeg',
        rating: 5,
        reviewCount: 7708,
        category: 5,
        price: 368,
    },
    {
        id: 77987,
        name: 'Travelodge San Francisco Central',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/77/98/77987_v7.jpeg',
        rating: 1,
        reviewCount: 3711,
        category: 2,
        price: 59,
    },
    {
        id: 8068,
        name: 'The Pickwick Hotel San Francisco',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/80/68/8068_v8.jpeg',
        rating: 2,
        reviewCount: 3212,
        category: 4,
        price: 199,
    },
    {
        id: 8051,
        name: 'Hotel Nikko San Francisco',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/80/51/8051_v10.jpeg',
        rating: 5,
        reviewCount: 11804,
        category: 4,
        price: 650,
    },
    {
        id: 8002,
        name: 'Omni San Francisco Hotel',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/80/02/8002_v5.jpeg',
        rating: 5,
        reviewCount: 4868,
        category: 4,
        price: 475,
    },
    {
        id: 63895,
        name: 'Hotel Beresford',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/63/89/63895_v4.jpeg',
        rating: 2,
        reviewCount: 7021,
        category: 2,
        price: 89,
    },
    {
        id: 8075,
        name: 'Hotel Vertigo',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/80/75/8075_v6.jpeg',
        rating: 3,
        reviewCount: 2992,
        category: 3,
        price: 127,
    },
    {
        id: 8070,
        name: 'Hotel Union Square',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/80/70/8070_v4.jpeg',
        rating: 3,
        reviewCount: 4040,
        category: 3,
        price: 179,
    },
    {
        id: 7997,
        name: 'Hyatt Regency San Francisco',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/79/97/7997_v6.jpeg',
        rating: 5,
        reviewCount: 7599,
        category: 4,
        price: 379,
    },
    {
        id: 61755,
        name: 'Holiday Inn San Francisco-Golden Gateway',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/61/75/61755_v8.jpeg',
        rating: 3,
        reviewCount: 3749,
        category: 4,
        price: 189,
    },
    {
        id: 982929,
        name: 'Cow Hollow Motor Inn',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/98/29/982929_v1.jpeg',
        rating: 4,
        reviewCount: 1158,
        category: 2,
        price: 143,
    },
    {
        id: 1260277,
        name: 'Geary Parkway',
        type: 'Motel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/12/60/1260277_v5.jpeg',
        rating: 3,
        reviewCount: 1511,
        category: 0,
        price: 100,
    },
    {
        id: 7983,
        name: 'Comfort Inn By The Bay San Francisco',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/79/83/7983_v4.jpeg',
        rating: 3,
        reviewCount: 4655,
        category: 2,
        price: 125,
    },
    {
        id: 8058,
        name: 'Phoenix Hotel',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/80/58/8058_v2.jpeg',
        rating: 4,
        reviewCount: 1489,
        category: 3,
        price: 179,
    },
    {
        id: 8072,
        name: 'Villa Florence',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/80/72/8072_v8.jpeg',
        rating: 3,
        reviewCount: 4268,
        category: 4,
        price: 181,
    },
    {
        id: 59531,
        name: 'Buena Vista Motor Inn',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/59/53/59531_v3.jpeg',
        rating: 2,
        reviewCount: 3157,
        category: 2,
        price: 156,
    },
    {
        id: 66830,
        name: 'Grand Hyatt San Francisco',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/66/83/66830_v8.jpeg',
        rating: 5,
        reviewCount: 6336,
        category: 4,
        price: 369,
    },
    {
        id: 57592,
        name: 'Staypineapple, An Elegant Hotel, Union Square',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/57/59/57592_v6.jpeg',
        rating: 4,
        reviewCount: 1633,
        category: 4,
        price: 249,
    },
    {
        id: 79366,
        name: 'Hotel The Club Donatello',
        type: 'Hotel',
        image:
            'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,f_auto,h_310,q_auto,w_551/itemimages/79/36/79366_v6.jpeg',
        rating: 5,
        reviewCount: 4363,
        category: 4,
        price: 267,
    },
];
