// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const list: string;
export const isLoading: string;
export const item: string;
